name: CreateRelease
on:
  workflow_dispatch:
    inputs:
      execution:
        description: 'Type of execution'
        required: true
        default: 'Manual'
        type: choice
        options:
          - Manual
  push:
    tags:
      - v*

jobs:
  build:
    name: Draft release action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0 # v7.0.0
        with:
          script: |
            github.rest.repos.createRelease({
              owner: "${{ github.repository_owner }}",
              repo: "abort-mission-maven-plugin",
              tag_name: "${{ github.ref_name }}",
              generate_release_notes: true,
              draft: true
            });
